:lipstick: [FLAV-196] Improved BeanListItem styles
h1r0mu/flavorbook pull request #127
Opened 2021-10-27 14:23 UTC by h1r0mu

The current beans page doesn't look good.

Changed styles based on Vivino.

Details:

- Changed to obtain chip colors from Flavor wheel data
- Improved fonts
- Improved layouts
- Added packages to get flags according to country names

経緯は上記の通り．

レビュー項目:
- beansページ (mybeans) 
  - 描写の時間が長すぎないか (重たい処理を追加したため)
  - Flavorに応じた色 (Flavor Wheelと一致する) のチップが表示されているか
  - 表示が崩れている箇所がないか
  - nullなど不適切な文字が表示されていないか

2021-10-31 22:46 UTC, Hironori8 commented
動作確認をした結果、上記項目において問題はなかったです。
ただ細かい点ですが、チップ間の余白が0だと思うので、余白がある方が見やすいのではないかと思いました。

2021-10-31 23:02 UTC, Hironori8 requested changes

2021-11-01 13:24 UTC, h1r0mu commented on src/features/myBeans/BeanListItem.js
> +      nameToFlag = { ...nameToFlag, ...{ [country.name]: country.emoji } };
修正しました．

2021-11-01 22:41 UTC, yukFuruya reviewed
RV項目のうち，
- 表示が崩れている箇所がないか
について，全画面表示の場合は問題ないですが，
画面を半分くらいの横幅にすると，画像にbeanの情報がかぶる状態になります．(下記画像参照)
![Screen Shot 2021-11-02 at 7 38 44](https://user-images.githubusercontent.com/45028786/139751534-4c5d845f-fc29-4f19-af65-60d98f863df8.png)

2021-11-02 11:59 UTC, Hironori8 commented on src/features/myBeans/BeanListItem.js
> +      nameToFlag = { ...nameToFlag, ...{ [country.name]: country.emoji } };
確認しました！

2021-11-03 11:31 UTC, h1r0mu commented
> RV項目のうち，
> 
>     * 表示が崩れている箇所がないか
>       について，全画面表示の場合は問題ないですが，
>       画面を半分くらいの横幅にすると，画像にbeanの情報がかぶる状態になります．(下記画像参照)
>       ![Screen Shot 2021-11-02 at 7 38 44](https://user-images.githubusercontent.com/45028786/139751534-4c5d845f-fc29-4f19-af65-60d98f863df8.png)

修正しました．

2021-11-03 12:15 UTC, yukFuruya commented
私用で出かけてました．レスポンスが遅くなってすみません．iPhoneの場合は，大丈夫そうです．
iPad系だと上手く出力がされていなかったみたいなんですけど，どうしましょうか？
１回マージさせて次回のスプリントでタスク切る感じですかね...?
<img width="1440" alt="Screen Shot 2021-11-03 at 21 12 44" src="https://user-images.githubusercontent.com/45028786/140058227-ea311c6d-8b60-4d04-a260-cee7de454691.png">

2021-11-03 13:49 UTC, h1r0mu commented
> 私用で出かけてました．レスポンスが遅くなってすみません．iPhoneの場合は，大丈夫そうです． iPad系だと上手く出力がされていなかったみたいなんですけど，どうしましょうか？ １回マージさせて次回のスプリントでタスク切る感じですかね...? <img alt="Screen Shot 2021-11-03 at 21 12 44" width="1440" src="https://user-images.githubusercontent.com/45028786/140058227-ea311c6d-8b60-4d04-a260-cee7de454691.png">

修正しました

2021-11-03 14:11 UTC, yukFuruya commented
@h1r0mu ありがとうございます．大丈夫そうです．

2021-11-03 14:11 UTC, yukFuruya approved these changes

2021-11-03 14:21 UTC, h1r0mu commented
> @h1r0mu ありがとうございます．大丈夫そうです．

@yukFuruya 
最新MergeコミットがMergeコミットで上書きされているようですが何故でしょうか

2021-11-03 14:24 UTC, yukFuruya commented
@h1r0mu conflictしていて反映された内容を確認できなかったからです．

2021-11-03 14:35 UTC, h1r0mu commented
> @h1r0mu conflictしていて反映された内容を確認できなかったからです．

@yukFuruya その場合はコメントでConflictを指摘してもらったほうが助かります．Assignee以外がCommitを追加すると責任分界点が曖昧になってしまいます．
FYI, Conflictしていたとしてもyarn startに支障はないはず．

2021-11-03 14:37 UTC, yukFuruya commented
@h1r0mu 勉強しました．ありがとうございます．

2021-11-03 22:28 UTC, Hironori8 approved these changes

2021-11-03 22:28 UTC, merged