[FLAV-193] Add support for beans of no image.
h1r0mu/flavorbook pull request #128
Opened 2021-10-27 22:13 UTC by yukFuruya

### 実施事項
画像を登録しなくてもmybeansに表示されるようにしました．

### 確認項目
- [ ]  画像を登録しなくても，mybeansに登録した豆のカードが確認できる．

2021-10-31 22:40 UTC, Hironori8 requested changes

2021-10-31 22:40 UTC, Hironori8 commented on src/features/myBeans/BeanListItem.js
>      if (bean.pictureURL) {
cafe-76~の箇所はあとで見た時になんの画像かわからないから、default_pictureとかに変えてほしい
あとfetchImageSrcが冗長になってるから変数だけをbean.pictureURLの有無で変える方がよいかも
下の例みたいな感じ

```
const url = bean.pictureURL? bean.pictureURL : "default_picture.jpg";
fetchImageSrc("member/" + url);
```

2021-10-31 22:40 UTC, Hironori8 commented
動作確認は問題なし

2021-11-01 11:34 UTC, h1r0mu requested changes

2021-11-01 11:34 UTC, h1r0mu commented on src/features/myBeans/BeanListItem.js
>      if (bean.pictureURL) {
これ先日デイリーかなんかで話したとおり画像をローカルに置くようにしてください．

2021-11-03 14:48 UTC, h1r0mu requested changes

2021-11-03 14:48 UTC, h1r0mu commented on src/features/myBeans/BeanListItem.js
> +import Image from "../../data/default_beanpic.png";
```suggestion
import defaultImage from "../../data/default_beanpic.png";
```

コンポーネント以外はCapitalにしないようにしましょう

2021-11-03 14:48 UTC, h1r0mu commented on src/features/myBeans/BeanListItem.js
> +    bean.pictureURL ? fetchImageSrc("member/" + bean.pictureURL) : setImageSrc(Image)
```suggestion
    bean.pictureURL ? fetchImageSrc("member/" + bean.pictureURL) : setImageSrc(defaultImage)
```

2021-11-03 14:57 UTC, yukFuruya commented
@Hironori8 @h1r0mu 一通り指摘内容を反映しました．ご確認よろしくお願いします．

2021-11-03 15:37 UTC, yukFuruya commented
> > @Hironori8 @h1r0mu 一通り指摘内容を反映しました．ご確認よろしくお願いします．
> 
> @yukFuruya rebaseだけお願いします． Commitを1つにまとめてください．

@h1r0mu まとめました！

2021-11-03 16:01 UTC, h1r0mu approved these changes
:+1:

2021-11-03 22:26 UTC, Hironori8 approved these changes

2021-11-03 22:27 UTC, Hironori8 approved these changes

2021-11-03 22:27 UTC, merged