[FLAV-173] Add overview to README.
h1r0mu/flavorbook pull request #130
Opened 2021-11-01 11:52 UTC by RyuHosei

Getting Started までの内容を新規に追加しました．Test の部分は実行コマンドのみ記載しています．

レビュー項目
- Features の内容
- Requirement の内容
- Installation の内容
- Getting Started の内容

2021-11-01 12:11 UTC, Hironori8 approved these changes

2021-11-01 22:56 UTC, Hironori8 commented on README.md
> +## Test
testを個別でやる場合どうするかも書いておくとよいかも

2021-11-01 23:07 UTC, yukFuruya reviewed
RV項目のところについては，中野が言っているところ以外は大丈夫そう．
ただ，Logoの画像だけ見れない状態になっていたので，のちのち修正は必要そうだね
![Screen Shot 2021-11-02 at 8 06 55](https://user-images.githubusercontent.com/45028786/139753635-69a670fb-dba1-42c7-854d-749e8ca729fb.png)

2021-11-01 23:47 UTC, h1r0mu requested changes

2021-11-01 23:47 UTC, h1r0mu commented on README.md
> +![LICENSE](https://img.shields.io/badge/LICENSE-MIT-76DO4B.svg?style=plastic)
```suggestion
![LICENSE](https://img.shields.io/badge/LICENSE-MIT-76DO4B.svg?style=plastic)
[![Total alerts](https://img.shields.io/lgtm/alerts/g/h1r0mu/flavorbook.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/h1r0mu/flavorbook/alerts/)
[![Language grade: JavaScript](https://img.shields.io/lgtm/grade/javascript/g/h1r0mu/flavorbook.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/h1r0mu/flavorbook/context:javascript)
[![Lint and tests](https://github.com/h1r0mu/flavorbook/actions/workflows/lint.yml/badge.svg)](https://github.com/h1r0mu/flavorbook/actions/workflows/lint.yml)
```

mainでCIの結果のバッジを載せているのでこれらも含めてください

2021-11-01 23:47 UTC, h1r0mu commented on README.md
> + ```
```suggestion
 ```sh
git clone https://github.com/h1r0mu/flavorbook.git
 ```
```

2021-11-01 23:47 UTC, h1r0mu commented on README.md
> + ```
```suggestion
 ```sh
yarn test
 ```
```

2021-11-01 23:47 UTC, h1r0mu commented on README.md
> + ```
```suggestion
 ```sh
yarn install
 ```
```

2021-11-01 23:47 UTC, h1r0mu commented on README.md
> + ```
```suggestion
 ```sh
yarn start
 ```
```

2021-11-02 11:33 UTC, RyuHosei commented on README.md
> + ```
```sh
がローカルの環境でうまく機能せず，```console で修正しました．

2021-11-02 11:34 UTC, RyuHosei commented on README.md
> +![LICENSE](https://img.shields.io/badge/LICENSE-MIT-76DO4B.svg?style=plastic)
バッジ追加しました，ご確認をお願いします．

2021-11-02 12:14 UTC, h1r0mu commented on README.md
> + ```
`$`の除去だけお願いします

2021-11-03 14:41 UTC, RyuHosei commented on README.md
> + ```
$ 除去しました

2021-11-03 22:33 UTC, RyuHosei commented on README.md
> +## Test
追記しました．

2021-11-06 15:54 UTC, h1r0mu requested changes

2021-11-06 15:54 UTC, h1r0mu commented on README.md
> +yarn test XXXXX.test.js
```suggestion
yarn test <path>
```

2021-11-06 15:54 UTC, h1r0mu commented on README.md
> +yarn test XXXXX.test.js
ここだけ修正お願いします

2021-11-07 13:36 UTC, RyuHosei commented on README.md
> +yarn test XXXXX.test.js
修正しました

2021-11-08 12:37 UTC, h1r0mu approved these changes
:+1:

2021-11-08 12:37 UTC, merged