[FLAV-68-0] Add Snapshot Test without failing test
h1r0mu/flavorbook pull request #131
Opened 2021-11-02 13:55 UTC by Hironori8

2021-11-03 11:20 UTC, h1r0mu requested changes
propの型でエラーが出ているので，更にMockが必要ですね．
Firestoreに関しては[Stub](https://qiita.com/Kesin11/items/43bbc06524aa31c1fd2c)が使えそうなので，もしCIにこのStubが組み込めるなら，いちいちMockするよりこれを使ってDummyデータを入れたFirestoreのエミュレータを使ったほうがいいかも知れません．

```
  ● Console

    console.error
      Warning: Failed prop type: Invalid prop `value` of type `object` supplied to `ComplexButton`, expected `string`.
          at ComplexButton (/home/owner/.ghq/github.com/h1r0mu/flavorbook/src/features/bean/ComplexButton.js:86:26)
          at Profile (/home/owner/.ghq/github.com/h1r0mu/flavorbook/src/features/bean/Profile.js:18:20)
          at Router (/home/owner/.ghq/github.com/h1r0mu/flavorbook/node_modules/react-router/cjs/react-router.js:99:30)
          at BrowserRouter (/home/owner/.ghq/github.com/h1r0mu/flavorbook/node_modules/react-router-dom/cjs/react-router-dom.js:67:35)
          at Provider (/home/owner/.ghq/github.com/h1r0mu/flavorbook/node_modules/react-redux/lib/components/Provider.js:21:20)

      40 |         disabled={disabled}
      41 |       />
    > 42 |       <ComplexButton
         |       ^
      43 |         onClick={() => inputElement.current && inputElement.current.click()}
      44 |         value={<PhotoCamera />}
      45 |         imageUrl={bean.imageURL}

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:117:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:93:5)
      at checkPropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:620:11)
      at validatePropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1072:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1192:7)
      at Profile (src/features/bean/Profile.js:42:7)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8744:13)

```

2021-11-03 11:20 UTC, h1r0mu commented on src/features/bean/__test__/beanSlice.test.js
> +import beanSlice from "../beanSlice.js";
beanSliceはComponentではないのでテスト対象から外して良いです

2021-11-03 11:20 UTC, h1r0mu commented on src/features/common/__test__/AuthFireRoute.test.js
> +import AuthFireRoute from "../AuthFireRoute.js";
ditto

AuthFireRouteは単純なsnapShotではなく，currentUserによって返すコンポーネントが変わることを確認するテストにするべきだと思います．
今回は見送ってあとで実装しましょう．

2021-11-03 11:20 UTC, h1r0mu commented on src/features/common/__test__/Dialog.test.js
> +import Dialog from "../Dialog.js";
最新のdevelopで削除されているので，削除してください．

https://github.com/h1r0mu/flavorbook/tree/develop/src/features/common

2021-11-03 11:20 UTC, h1r0mu commented on src/features/common/__test__/Tile.test.js
> +import Tile from "../Tile.js";
ditto

2021-11-03 11:20 UTC, h1r0mu commented on src/features/myBeans/Page.js
> +  console.log(beans);
```suggestion
```

2021-11-03 11:20 UTC, h1r0mu commented on src/features/myBeans/__test__/beanSlice.test.js
> +import beanSlice from "../beansSlice.js";
ditto

2021-11-03 11:20 UTC, h1r0mu commented on src/features/myBeans/__test__/beansFiltersSlice.test.js
> +import beansFiltersSlice from "../beansFiltersSlice.js";
ditto

2021-11-03 11:20 UTC, h1r0mu commented on src/features/shop/__test__/shopSlice.test.js
> +import shopSlice from "../shopSlice.js";
ditto

2021-11-03 11:20 UTC, h1r0mu commented on src/features/user/__test__/userSlice.test.js
> +import userSlice from "../userSlice.js";
ditto

2021-11-06 07:48 UTC, yukFuruya reviewed
動作確認しかできなかったけど，テストは全部通ってた👍

2021-11-08 12:01 UTC, Hironori8 commented on src/features/bean/__test__/beanSlice.test.js
> +import beanSlice from "../beanSlice.js";
削除しました。

2021-11-08 12:01 UTC, Hironori8 commented on src/features/common/__test__/AuthFireRoute.test.js
> +import AuthFireRoute from "../AuthFireRoute.js";
削除しました。

2021-11-08 12:01 UTC, Hironori8 commented on src/features/common/__test__/Tile.test.js
> +import Tile from "../Tile.js";
削除しました。

2021-11-08 12:02 UTC, Hironori8 commented on src/features/myBeans/__test__/beanSlice.test.js
> +import beanSlice from "../beansSlice.js";
削除しました。

2021-11-08 12:02 UTC, Hironori8 commented on src/features/myBeans/__test__/beansFiltersSlice.test.js
> +import beansFiltersSlice from "../beansFiltersSlice.js";
削除しました。

2021-11-08 12:02 UTC, Hironori8 commented on src/features/shop/__test__/shopSlice.test.js
> +import shopSlice from "../shopSlice.js";
削除しました。

2021-11-08 12:02 UTC, Hironori8 commented on src/features/user/__test__/userSlice.test.js
> +import userSlice from "../userSlice.js";
削除しました。

2021-11-08 12:05 UTC, Hironori8 commented on src/features/common/__test__/Dialog.test.js
> +import Dialog from "../Dialog.js";
削除しました。

2021-11-08 23:42 UTC, h1r0mu approved these changes
:+1:

2021-11-10 12:54 UTC, merged