[FLAV-176] Add comments to the functions in /feature/bean
h1r0mu/flavorbook pull request #137
Opened 2021-11-09 12:14 UTC by Yamafumi000

遅くなりましたが/feature/bean以下のファイルへコメントを付与しました．
全てではありませんが，確認よろしくお願いします．

2021-11-09 14:04 UTC, h1r0mu requested changes
rootディレクトリで`yarn prettier --write .`を実行するとAutoformatされるので，実行後もう一度Pushしてください．
ProfileがDevelopとConflictしているようなので，修正お願いします．

2021-11-12 16:49 UTC, h1r0mu requested changes

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Autocomplete.js
> + * @returns {Component} 豆の情報を入力するフォームを作成する関数
```suggestion
 * @returns {Component} 豆の情報を入力するフォームのコンポーネント
```

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Autocomplete.js
> + * 豆の情報を入力するフォームを作成する関数.
```suggestion
 * 豆の情報を入力するフォームの関数コンポーネント.
```

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/ComplexButton.js
> + * 豆の写真をサイトにアップロードするフォームを作成する関数
ditto

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Page.js
> + * 豆の登録ページを作成する関数
ditto

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Profile.js
> + * 写真や購入店舗，産地などの豆の大枠の情報を入力する領域を作成する関数
ditto

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Profile.js
> + * @param {bool} disabled その情報が入力可能かどうかを示す値. trueで不可，falseで可
```suggestion
 * @param {bool} disabled 情報が入力可能かどうかを示す値. trueで不可，falseで可
```

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Profile.js
> +    //URL.createObjectURL()は廃止予定なので，別の書き方に変える必要あり？
出典を教えてもらえますか．

確信があるようならTODOコメントにしておいてください．TODOで検索すると既存のコメントが引っかかると思うのでそちらを参考に

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Rating.js
> + * Clean cup等のRatingのコンポーネントを作成する関数
ditto

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Score.js
> + * scoreページのratingとmemoを一つの入力欄としてまとめて作成する関数
ditto

2021-11-12 16:49 UTC, h1r0mu commented on src/features/bean/Score.js
> + * Clean cup(クリアさ)などの情報を入力するScoreページのコンポーネントを作成する関数
```suggestion
 * 豆の評価を入力するScoreページの関数コンポーネント
```

あまり具体的に書くとコードを変更したとき面倒なので

2021-11-12 16:49 UTC, h1r0mu commented
コメントしました

2021-11-15 13:36 UTC, Yamafumi000 commented on src/features/bean/Profile.js
> +    //URL.createObjectURL()は廃止予定なので，別の書き方に変える必要あり？
webRTCを実装しているサイトで<video>属性に対して，video.src = URL.createObjectURL(stream)と記述していた場合に video.srcObject = streamに変更することが推奨されているのであって，画像に関しては特に問題ないようです．お騒がせしました．

参考
- https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL
- https://wiki.onakasuita.org/pukiwiki/?URL.createObjectURL

2021-11-15 15:26 UTC, h1r0mu commented
@Yamafumi000 すみません．説明不足でしたが，関数コンポーネントは関数と使い方が異なるので関数コンポーネントと明記して貰えると助かります．

2021-11-15 15:28 UTC, h1r0mu requested changes
@Yamafumi000 すみません．説明不足でしたが，関数コンポーネントは関数と使い方が異なるので関数コンポーネントと明記して貰えると助かります．
むしろ，それがただの関数なのかコンポーネントなのかを見分ける助けになるのがコメントの役割だと思います．

2021-11-17 12:12 UTC, h1r0mu approved these changes
:+1:

2021-11-17 12:12 UTC, merged