Update Profile Update Page and Member Page
h1r0mu/flavorbook pull request #92
Opened 2021-08-04 23:02 UTC by Hironori8

プロフィールの更新ページとプロフィールページの機能実装とUIの更新をおこないました。

2021-08-05 00:03 UTC, h1r0mu requested changes
コメントしました． 

あと，これ解消したほうが良いかも．
![image](https://user-images.githubusercontent.com/23627425/128270335-c9e5618c-c577-4319-b949-11ca86d75f9f.png)

2021-08-05 00:03 UTC, h1r0mu commented on src/features/signup/Signup.js
> +  | { type: "setAccountName", payload: string }
type Actionのブロックに書いてあるのってTypeScript用のAnnotationではないですか?
そうであれば削除してください．

[15行目](https://github.com/h1r0mu/flavorbook/pull/92/files#diff-c9de0c2acee8275f8b3b877f2cb8947a962a38da6c3ba42a667770c07839ad8dR15)
のものも同様にTypescriptのAnnotationと思われます．

```
const useStyles = makeStyles((theme: Theme)
```

このページとLogin.jsは，同様の箇所が多く見られるので要不用を確認して，不要なら削除してください．

2021-08-12 14:54 UTC, Hironori8 commented on src/contexts/AuthContext.js
> +        db.collection("users")
変更しました

2021-08-12 14:54 UTC, Hironori8 commented on src/features/signup/Signup.js
> +  | { type: "setAccountName", payload: string }
Annotationの部分を削除しました

2021-08-12 14:59 UTC, Hironori8 commented on src/contexts/AuthContext.js
> +  async function signup(email, password, displayName) {
thenの処理をasync/awaitに変更しました。

2021-08-12 14:59 UTC, Hironori8 commented on src/contexts/AuthContext.js
> +  async function updateProfile(profileData) {
　async/await処理に変更

2021-08-12 14:59 UTC, Hironori8 commented on src/features/login/Login.js
> +const useStyles = makeStyles((theme) =>
Annotationを削除しました

2021-08-12 14:59 UTC, Hironori8 commented on src/features/login/Login.js
> -type Action =
Annotationを削除しました

2021-08-12 14:59 UTC, Hironori8 commented on src/features/signup/Signup.js
> -const useStyles = makeStyles((theme: Theme) =>
Annotationを削除しました。

2021-08-12 14:59 UTC, Hironori8 commented on src/features/signup/Signup.js
> -// アクションの型指定
Annotationを削除しました。

2021-08-15 23:16 UTC, h1r0mu requested changes

2021-08-15 23:17 UTC, h1r0mu commented on src/features/common/Avater.js
> +import React from "react";
もしプレースホルダーとして置いているだけなら `user` 以下に配置してください．

2021-08-15 23:22 UTC, h1r0mu commented on src/features/common/Avater.js
> +        src="./static/coffee_login.jpg"
画像を外から挿せるようにだけしてください

2021-08-16 23:03 UTC, Hironori8 commented on src/features/signup/Signup.js
>    email: string,
Annotation削除しました

2021-08-16 23:04 UTC, Hironori8 commented on src/features/signup/Signup.js
>    email: "",
Annotation削除しました

2021-08-16 23:04 UTC, Hironori8 commented on src/features/signup/Signup.js
> +  const handleAccountNameChange: React.ChangeEventHandler<HTMLInputElement> = (
Annotation削除しました

2021-08-16 23:17 UTC, Hironori8 commented on src/features/user/Member.js
> +  console.log(currentUser.uid);
削除しました

2021-08-16 23:17 UTC, Hironori8 commented on src/features/user/Member.js
> +                    <Link to={url}>プロフィール変更</Link>
ハードコーディングの仕様に変更しました。

2021-08-16 23:20 UTC, Hironori8 commented on src/features/user/UpdateProfile.js
> +  console.log(id);
削除しました。

2021-08-16 23:38 UTC, Hironori8 commented on src/features/common/Avater.js
> +        src="./static/coffee_login.jpg"
propsを使用して外からさせるようにしました

2021-08-17 13:14 UTC, Hironori8 commented on src/features/user/UpdateProfile.js
> +  console.log(id);
削除しました

2021-08-17 13:14 UTC, Hironori8 commented on src/features/common/Avater.js
> +        src="./static/coffee_login.jpg"
画像を外から挿せるようにしました

2021-08-17 23:22 UTC, h1r0mu requested changes

2021-08-18 23:46 UTC, h1r0mu requested changes
ログインボタンを押したときに飛ぶ先が `member` のままのようです．
他にも同様の箇所がないかチェックしてください．

https://github.com/h1r0mu/flavorbook/pull/92/files#diff-db07f723d8825c62ee5745635eac33f255be6dbff7f636e3bfdfae54a3ec6baeR155

コミットが多くなっているので，rebaseして似たコミットを一つにsquashしてもらえると助かります．

2021-08-29 22:47 UTC, h1r0mu approved these changes
@Hironori8 :+1:

2021-08-29 22:47 UTC, merged