Created a view of Member page. Issue/flav 86
h1r0mu/flavorbook pull request #93
Opened 2021-08-05 11:35 UTC by yukFuruya

メンバーページのView部分を作りました．

2021-08-09 22:25 UTC, h1r0mu commented
@yukFuruya prettierのエラー解消してください

2021-08-10 00:00 UTC, h1r0mu requested changes
@yukFuruya コメントしました

2021-08-10 22:43 UTC, yukFuruya commented on package.json
> -    "@material-ui/core": "^4.11.3",
どこかの段階でpullしてきたものをレンダリングした際に，material-ui関連で怒られたので，結局アップデートしたんですよね...
もしかしたら必要がなかったのかもしれませんが...

2021-08-18 23:56 UTC, h1r0mu requested changes

2021-08-18 23:56 UTC, h1r0mu commented on src/features/shop/ShopInfo.js
> +// };
```suggestion
```

2021-08-18 23:56 UTC, h1r0mu commented on src/App.js
> +                <Route path="/shop">
```suggestion
                <Route path="/shop/:id">
```

URLに表示するshopのshopIdを指定できるようにしてください．
https://reactrouter.com/web/api/Hooks/useparams

2021-08-18 23:56 UTC, h1r0mu commented on src/features/myBeans/BeanListItem.js
> +    console.log(bean);
```suggestion
```

2021-08-18 23:56 UTC, h1r0mu commented on src/features/shop/ShopInfo.js
> +  useEffect(() => dispatch(fetchShop("jE2CiMwTUUKIwfH11xO6")), []);
shopIdをuseParamsで取るようにしてください

c.f.,
https://github.com/h1r0mu/flavorbook/blob/main/src/features/bean/PageEdit.js#L10

2021-08-18 23:56 UTC, h1r0mu commented on src/features/shop/ShopInfo.js
> +    return <p>loading</p>;
MUIのぐるぐる使ってください．
https://material-ui.com/components/progress/#circular

2021-08-18 23:56 UTC, h1r0mu commented on src/features/shop/ShopInfo.js
> +              ご注文ごとに生豆から焙煎するコーヒー豆専門店
店のディスクリプションはDBに登録するようにしたいので，DB側にフィールドを追加してください．

2021-08-18 23:56 UTC, h1r0mu commented
一段落した段階でrebaseして似たcommitをsquashしてください．

`git rebase -i origin/main`

2021-08-23 22:21 UTC, yukFuruya commented
@h1r0mu プルリク反映させました．ご確認よろしくお願いします．

2021-08-24 22:37 UTC, h1r0mu approved these changes
@yukFuruya :+1:

2021-08-24 22:37 UTC, merged