[FLAV-133] Implement Uploading Avatar and Showing it.
h1r0mu/flavorbook pull request #97
Opened 2021-09-05 22:39 UTC by Hironori8

以下2点の機能を実装しました。

* メンバーページにアカウントの画像を表示する機能
* プトフィール変更ページでアカウントの画像を変更する機能

以下の項目を見ていただけるとありがたいです。

- [ ] Avatarの変更をする機能において、余分なコードはないか

- [ ] バグになってまいそうな箇所はないか

よろしくお願いします

2021-09-06 22:32 UTC, yukFuruya reviewed
コメントしました．

2021-09-06 22:32 UTC, yukFuruya commented on src/features/user/Member.js
> +            <Avater src={imageSrc} />
些細だけど，Avatarかも

2021-09-06 22:32 UTC, yukFuruya commented on src/features/user/UpdateProfile.js
> +import Avater from "../common/Avater";
同上

2021-09-06 22:32 UTC, yukFuruya commented on src/features/user/UpdateProfile.js
> +    },
avatarとuploadが全く一緒だから固めても大丈夫だったりする？

2021-09-06 23:14 UTC, h1r0mu commented
![image](https://user-images.githubusercontent.com/23627425/132265065-de6f0589-d062-4731-a665-186ba7a55a1b.png)

avatarの画像が未登録だとエラーになるようです．

2021-09-07 22:31 UTC, yukFuruya commented
<img width="722" alt="Screen Shot 2021-09-08 at 7 27 46" src="https://user-images.githubusercontent.com/45028786/132418621-981d38e8-eeeb-47a9-8422-e8055df4bd12.png">
usernameを「kくん」から「k太郎くん」のように，間に文章を差し込もうとしたら，
カーソルが1文字目の段階で一番右に遷移して「kくん太郎」のようになってしまいます．

でも，このバグは該当範囲ではないかな...？

2021-09-07 23:05 UTC, Hironori8 commented on src/features/user/Member.js
> +            <Avater src={imageSrc} />
修正完了

2021-09-07 23:05 UTC, Hironori8 commented on src/features/user/UpdateProfile.js
> +import Avater from "../common/Avater";
修正完了

2021-09-07 23:09 UTC, Hironori8 commented on src/features/user/UpdateProfile.js
> +    },
今後の修正がしやすいようにこのように記述

2021-09-07 23:12 UTC, yukFuruya commented on src/features/user/UpdateProfile.js
> +    },
修正なしで認識合いました

2021-09-07 23:18 UTC, h1r0mu requested changes

2021-09-07 23:18 UTC, h1r0mu commented on src/features/user/Member.js
> +    fetchAvatarSrc();
![image](https://user-images.githubusercontent.com/23627425/132265065-de6f0589-d062-4731-a665-186ba7a55a1b.png)

この部分で必ず `${currentUser.uid}.png` の画像を自動的に拾って来るようになっているため．
avatarの画像が未登録だとエラーになるようです．

2021-09-07 23:18 UTC, h1r0mu commented on src/features/user/UpdateProfile.js
> +  const [imageUrl, setImageUrl] = useState("");
プロフィールの更新画面でアバターが表示されないです．

https://github.com/h1r0mu/flavorbook/pull/97/files#diff-8413395fde3f5520b7169e692d3b9a11a763c35461efbabf4536ea72eb7dff4eR56-R63

Memberコンポーネントのコードをそのまま持ってきてimageUrlにセットすれば良いと思います．

画像取ってくるロジックはAvaterで必ず必要になると思うので，可能なら別コンポーネントとして切り離してください．

2021-09-08 22:56 UTC, Hironori8 commented on src/features/user/Member.js
> +    fetchAvatarSrc();
avatarが未登録の場合にnull値を代入するように設定しました

2021-09-08 23:39 UTC, Hironori8 commented on src/features/user/UpdateProfile.js
> +  const [imageUrl, setImageUrl] = useState("");
プロフィール画面でアバターが表示できるようにしました。
また画像をとってくるロジックをuserディレクトリのFetchAvatar.jsに切り離しました。

2021-09-14 15:36 UTC, h1r0mu commented on src/features/user/FetchAvatar.js
> +  setImageUrl(imageUrl);
上のコメントの実現は無理そうなので，これはこのまま残しましょう．

async/awaitに対する理解が間違っていたようです (前に同じ問題に遭遇したはずなんですが完全に忘れていました)．
awaitはcallbackやPromiseの糖衣構文なので，背後ではcallback関数と同じ仕組みが動いています．
callback関数は，非同期関数の結果を引数に受け取ってなにか処理をする関数です．
非同期関数の結果というのは`result  = await asyncFunc()`でいうところのresultです．
このときのcallback関数に相当するのが
```
result = await asyncFunc()
callback(result)
```
でいうところのcallbackです．
というわけで，awaitの左辺はなにかの関数の引数である必要があります．

##### previousとcurrentという2つの文字列を受け取り1秒後にそれらを連結した文字列を返す非同期関数
```
function addString(previous, current){
  return new Promise((resolve, reject) => {
    setTimeout(
      () => {
        resolve(previous + ' ' + current)
      }, 
      1000
    )
  })
}
```

##### Promise
```
function addAll(){  
  addString('', 'A')
  .then(result => { // <- thenの引数に入れた無名関数がresolveに対応する．ちなみにerrorの引数に入れたものはrejectに対応する
    return addString(result, 'B')
  })
  .then(result => {
    return addString(result, 'C')
  })
  .then(result => {
    console.log(result) // Prints out " A B C"
  })
}
```

##### async/await

```
async function addAll(){
  let result = await addString('', 'A')
  result = await addString(result, 'B')
  result = await addString(result, 'C')
  console.log(toPrint) // Prints out " A B C"
}
addAll()
```

awaitの返り値は，callback関数に渡す引数に相当するので，次の関数の引数に使われるという前提

https://medium.com/front-end-weekly/callbacks-promises-and-async-await-ad4756e01d90

2021-09-14 15:39 UTC, h1r0mu approved these changes

2021-09-14 23:00 UTC, merged